name: C++ CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build-and-test-gcc:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y cmake ninja-build gcc-14 g++-14

    - name: Configure CMake with gcc
      run: cmake -B ${{github.workspace}}/build/gcc -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=g++-14
    - name: Build with gcc
      run: cmake --build ${{github.workspace}}/build/gcc
    - name: Test with gcc
      working-directory: ${{github.workspace}}/build/gcc
      run: ctest

  build-and-test-clang:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Add LLVM Repository
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        
    - name: Install dependencies
      run: |
           sudo apt-get update
           sudo apt-get install -y cmake g++-14 ninja-build clang-18 libfmt-dev libc++-18-dev libc++abi-18-dev

    - name: Configure CMake with clang++-18 llvm libc++
      run: cmake -B ${{github.workspace}}/build/clang-18-libcxx -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_CXX_FLAGS="-stdlib=libc++"
    - name: Build with clang++-18 llvm libc++
      run: cmake --build ${{github.workspace}}/build/clang-18-libcxx
    - name: Test with clang++-18 llvm libc++
      working-directory: ${{github.workspace}}/build/clang-18-libcxx
      run: ctest

    - name: Configure CMake with clang++-18 gnu libstdc++
      run: cmake -B ${{github.workspace}}/build/clang-18 -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=clang++-18
    - name: Build with clang++-18
      run: cmake --build ${{github.workspace}}/build/clang-18
    - name: Test with clang++-18
      working-directory: ${{github.workspace}}/build/clang-18
      run: ctest
      
  build-and-test-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake with MSVC
      run: cmake -B ${{github.workspace}}/build/msvc -DCMAKE_BUILD_TYPE=Debug
    - name: Build with MSVC
      run: cmake --build ${{github.workspace}}/build/msvc
    - name: Test with MSVC
      working-directory: ${{github.workspace}}/build/msvc
      run: ctest -C Debug

