name: C++ CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build-and-test-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build gcc g++ libfmt-dev

    - name: Configure CMake with gcc
      run: cmake -B ${{github.workspace}}/build/gcc -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=g++
    - name: Build with gcc
      run: cmake --build ${{github.workspace}}/build/gcc
    - name: Test with gcc
      working-directory: ${{github.workspace}}/build/gcc
      run: ctest

  build-and-test-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add LLVM Repository
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang-17 libfmt-dev
           sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100
           sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100
           
    - name: Configure Clang-17 as the default compiler
      run: |
        echo "CC=clang-17" >> $GITHUB_ENV
        echo "CXX=clang++-17" >> $GITHUB_ENV
        clang --version
        clang++ --version
        
    - name: Configure CMake with clang++-17
      run: cmake -B ${{github.workspace}}/build/clang-17 -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_CXX_COMPILER=clang++-17
    - name: Build with clang++-17
      run: cmake --build ${{github.workspace}}/build/clang-17
    - name: Test with clang++-17
      working-directory: ${{github.workspace}}/build/clang-17
      run: ctest
      
  build-and-test-msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake with MSVC
      run: cmake -B ${{github.workspace}}/build/msvc -DCMAKE_BUILD_TYPE=Debug
    - name: Build with MSVC
      run: cmake --build ${{github.workspace}}/build/msvc
    - name: Test with MSVC
      working-directory: ${{github.workspace}}/build/msvc
      run: ctest -C Debug

