name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build gcc g++ libboost-all-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -G "Ninja"
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      run: ctest --preset Test
