name: Update README Badge

on:
  push:
    tags:
      - 'v*'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Update README with latest tag
        run: |
          LATEST_TAG=${GITHUB_REF#refs/tags/}
          sed -i "s|Version:.*|Version: ${LATEST_TAG}|g" README.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update README with latest tag ${LATEST_TAG} [skip ci]"
          git push
